### ISSUE TITLE
The statistics are inconsistent with those in the paper

### ISSUE THREAD

**Issue by lanzhuzhu** [google-research-datasets/WebRED#2]
Thanks for making such an excellent dataset public!

I preprocessed the dataset to relabel negative samples whose positive rating is less than half. That is, the value of the feature "num_pos_raters"  is fewer than 2 in Dataset WebRED_h2+1 and fewer than 3 in Dataset WebRED_h5. 
However, I found the percentage of negative examples (%Neg) in the dataset is less than the number given in the paper.  Specifically,  my evaluations are:  %Neg in WebRED_h2+1 is 0.536 and 0.516 in WebRED_h5, while  %Neg should be up to 0.65 according to the paper. 

Is there anything wrong with my preprocessing?

**Comment by vinaysrao** [comment]
Hey, @lanzhuzhu thanks for asking this. We mention this in the paper (but the ReadMe will soon make this clearer too), but the released version of this dataset is not the full-sized version we used to report numbers in the paper (due to copyrights etc). So your numbers look right to me in the released version.
